### ISSUE TITLE
403: Forbidden For Airbnb iCal

### ISSUE THREAD

**Issue by rajeshsmallarc** [peterbraden/ical.js#102]
I am getting 403: Forbidden For Airbnb iCal. Please help.

**Comment by djclarkson** [comment]
@rajeshsmallarc  Getting the same. Did you find a solution?

**Comment by djclarkson** [comment]
To get around this you need to specify a user agent option for request. Here's an example: 

`var ical = require('node-ical');
var url = 'airbnb-ical-address'
var options = {
    headers: {
      'User-Agent': 'MY IPHINE 7s'
    }
  };

ical.fromURL(url, options, function(err, data) {
    if (err) console.log(err);
    console.log(data);
});`

**Comment by peterbraden** [comment]
See #110
