### ISSUE TITLE
Replace `request` lib with native http fetch or something lightweight

### ISSUE THREAD

**Issue by cktang88** [peterbraden/ical.js#108]
Request is a very bloated lib, simply to do an http request

**Comment by peterbraden** [comment]
I get many requests to replace 'request' and interestingly there are many different suggestions on what to replace it with.

At some point I will remove request entirely from the project, and let people do their own HTTP fetching - it is overkill to have it in this library.

If you'd like to make a PR removing it, then please feel free.

**Comment by ymchun** [comment]
hello, @peterbraden . I've create the PR https://github.com/peterbraden/ical.js/pull/110

please review, thanks a lot!

**Comment by peterbraden** [comment]
Fixed with #110
