### ISSUE TITLE
Update request to at least 2.54.0 to support NO_PROXY

### ISSUE THREAD

**Issue by fjakop** [peterbraden/ical.js#54]
Pleas upgrade the dependency `request` to a version >= 2.54.0. Since this version it honors the env variable `NO_PROXY`, so we can disable the proxy for testing purposes, like tests with `nock`.

**Comment by Powersource** [comment]
This looks to be fixed https://github.com/peterbraden/ical.js/blame/master/package.json#L18

But I'm having this issue https://github.com/request/request/issues/2040  
I'm gonna try to fix this tomorrow.
