### ISSUE TITLE
Remote Memory Exposure (VULNERABILITY)

### ISSUE THREAD

**Issue by nhubbard** [peterbraden/ical.js#58]
Through using [`request@2.40.0`](https://snyk.io/test/npm/request/2.40.0), we have a medium to highly serious issue of a Remote Memory Exposure bug in `request` and an ReDOS (Regular Expressions Denial of Service) issue through one of `request`'s dependencies, [`hawk@1.1.1`](https://snyk.io/test/npm/hawk/1.1.1). We can solve this by changing the version of `request` from 2.40.0 to >= 2.68.0.

**Comment by nhubbard** [comment]
A pull request will be added soon.

**Comment by nhubbard** [comment]
Pull request #59 is a fix for this issue.

**Comment by peterbraden** [comment]
Published 0.5.0 with the fix.

**Comment by nhubbard** [comment]
Thanks!
