### ISSUE TITLE
Un-escaping required for text fields

### ISSUE THREAD

**Issue by drauschenbach** [peterbraden/ical.js#6]
The following character sequences need to be un-escaped, for all text fields:  `\\`, `\;`, and `\,`.

RFC 2445 section 4.3.11:

```
text       = *(TSAFE-CHAR / ":" / DQUOTE / ESCAPED-CHAR)
 ; Folded according to description above
 ESCAPED-CHAR = "\\" / "\;" / "\," / "\N" / "\n")
    ; \\ encodes \, \N or \n encodes newline
    ; \; encodes ;, \, encodes ,
```

Sample LOCATION field from a VEVENT:

```
LOCATION:223 TWIN DOLPHIN DR\, Redwood City\, CA\, 94065-1514
```

**Comment by SavageWilliam** [comment]
Hey!

I'm also seeing `\"` handled oddly. 

EG 

This: `\"from limited individuality to unlimited being and deep peace\"`
 
 Becomes: `\from limited individuality to unlimited being and deep peace\`
