### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by MatthAddax** [peterbraden/ical.js#67]
I can't use the start and end date objects. I'm not familiar with JS Date object but I don't think I may be able to do anything with objects like these : 
`{ Mon, 31 Oct 2016 23:00:00 GMT tz: undefined }`
`{ Fri, 04 Nov 2016 23:00:00 GMT tz: '"Europe/Brussels"' }`

I'm I wrong or is this an issue to fix?

Thanks :)

**Comment by takkaria** [comment]
What do you mean 'don't think I may be able to do anything with objects like these'?  For information on how to use the Date object, see here: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by MatthAddax** [comment]
Hi,
I'm sorry for the post. I realized a little after posting it that this was the Date object and, effectively, I was able to do anything with it.

:)
