### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by tnguyen14** [peterbraden/ical.js#81]
Can new version of this module be released to take advantage of the recent fixes to update `request` version?

**Comment by armenzg** [comment]
@peterbraden Hello Peter, would you mind releasing a new version to npm? Please
Even though changes to request have been landed without a new release of ical we won't actually be able to take advantage of it:
https://snyk.io/test/npm/ical/0.5.0?severity=high&severity=medium&severity=low

**Comment by armenzg** [comment]
Here's the output of a cleanly installed ical:

> armenzg@armenzg-mbp backend$ npm ls request
> platform-health-dashboard@0.0.1 /Users/armenzg/repos/health/backend
> ├─┬ ical@0.5.0
> │ └── request@2.68.0

**Comment by armenzg** [comment]
I've released my own package until this is fixed.
