### ISSUE TITLE
All Day event indistinguishable from 24-hour event

### ISSUE THREAD

**Issue by newtang** [peterbraden/ical.js#94]
Since DTSTART and DTEND are converted to JS Date objects, it's impossible to tell if the given event was created as an All-Day event (meaning no time was specified) or an event that was 24 hours long.

**Comment by NicoSchtt** [comment]
I'm trying to get the dateOnly property with all day events and I don't get it

**Comment by boertel** [comment]
The latest npm package (`0.6.0`) doesn't have this feature.
You can install:
- `npm install peterbraden/ical.js#master` to always get latest
- or `npm install peterbraden/ical.js#e20ca9cb0d3fbc178cbb54ed3299a157a68db89b` to get just until the commit that contains `dateOnly` feature

**Comment by abrantes01** [comment]
@peterbraden is it possible to deploy a new tag on npm supporting this feature ?
